# Generated by Django 5.2.5 on 2026-09-27 07:04

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=accounts.models.gerar_codigo, max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Recuperação de Senha',
                'verbose_name_plural': 'Códigos de Recuperação de Senha',
                'ordering': ['-criado_em'],
            },
        ),
    ]
