# Generated by Django 5.2.5 on 2026-08-29 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rebanho', '0003_animal_data_ultimo_cio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REINCIDENCIA_MASTITE', 'Reincidência da Mastite'), ('CARENCIA', 'Fim de Carência'), ('CIO', 'Período de Cio (Atenção Reprodutiva)'), ('OUTRO', 'Outro Alerta')], max_length=50)),
                ('mensagem', models.TextField()),
                ('data_referencia', models.DateField(blank=True, help_text='Data relevante para o alerta (ex: fim da carência, data prevista do cio)', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='rebanho.animal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('animal', 'tipo'), name='unico_alerta_ativo_por_tipo_animal')],
            },
        ),
    ]
