# Generated by Django 5.2.5 on 2026-09-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('REINCIDENCIA_MASTITE', 'Reincidência da Mastite'), ('CARENCIA', 'Fim de Carência'), ('CIO', 'Período de Cio (Atenção Reprodutiva)'), ('CCS_ELEVADO', 'CCS Elevada (Risco de Mastite Subclínica)'), ('OUTRO', 'Outro Alerta')], max_length=50),
        ),
    ]
