# Generated by Django 5.2.5 on 2026-08-14 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brinco', models.CharField(help_text='Número de identificação/brinco do animal', max_length=30)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('raca', models.CharField(blank=True, max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['brinco'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'brinco'), name='brinco_unico_por_usuario')],
            },
        ),
    ]
