# Generated by Django 5.2.5 on 2026-08-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebanho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_animais/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('Fêmea', 'Fêmea'), ('Macho', 'Macho')], default='Fêmea', max_length=10),
        ),
    ]
