# Generated by Django 5.2.5 on 2026-08-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebanho', '0002_animal_foto_animal_observacoes_animal_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='data_ultimo_cio',
            field=models.DateField(blank=True, help_text='Data do último cio observado, usada para prever a próximo (~21 dias depois)', null=True),
        ),
    ]
