# Generated by Django 5.2.5 on 2026-09-20 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebanho', '0003_animal_data_ultimo_cio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_ccs', models.PositiveIntegerField(help_text='Contagem de Células Somáticas (células/mL)')),
                ('data_coleta', models.DateField()),
                ('laboratorio', models.CharField(blank=True, max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ccs', to='rebanho.animal')),
            ],
            options={
                'verbose_name': 'Registro de CCS',
                'verbose_name_plural': 'Registros de CCS',
                'ordering': ['-data_coleta', '-criado_em'],
            },
        ),
    ]
