# Generated by Django 5.2.5 on 2026-08-10 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='amostras/%Y/%m/%d/')),
                ('resultado', models.CharField(choices=[('Sem indícios de mastite', 'Sem indícios de mastite'), ('Possível presença de mastite', 'Possível presença de mastite'), ('Necessária avaliação adicional', 'Necessária avaliação adicional')], max_length=64)),
                ('confianca', models.FloatField(help_text='Percentual de confiança da IA (0 a 100)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análise',
                'verbose_name_plural': 'Análises',
                'ordering': ['-criado_em'],
            },
        ),
    ]
