# Generated by Django 5.2.5 on 2026-08-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rebanho', '0002_animal_foto_animal_observacoes_animal_peso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(blank=True, max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim_carencia', models.DateField(help_text='Data até quando o leite não deve ser misturado ao tanque')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='rebanho.animal')),
            ],
            options={
                'verbose_name': 'Tratamento',
                'verbose_name_plural': 'Tratamentos',
                'ordering': ['-data_fim_carencia'],
            },
        ),
    ]
